import type { AiProvider } from "./types";

export const geminiProvider: AiProvider = {
  async generateJson<T>(prompt: string, options: { temperature?: number; maxOutputTokens?: number } = {}) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) throw new Error("GEMINI_API_KEY environment variable is not configured.");
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=${key}`, {
      method: "POST", headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ contents: [{ role: "user", parts: [{ text: prompt }] }], generationConfig: { responseMimeType: "application/json", temperature: options.temperature ?? 0.2, maxOutputTokens: options.maxOutputTokens ?? 2048 } }),
    });
    if (!response.ok) throw new Error((await response.json().catch(() => null))?.error?.message || "Gemini request failed");
    const text = (await response.json())?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!text) throw new Error("No response text generated by AI model.");
    try { return JSON.parse(text.replace(/^```json\s*|\s*```$/g, "")) as T; } catch { throw new Error("AI returned invalid JSON."); }
  },
};
